class DiameterTerminationCause {
  static const int DI_TERMINATION_CAUSE_DIAMETER_LOGOUT = 1;
  static const int DI_TERMINATION_CAUSE_DIAMETER_SERVICE_NOT_PROVIDED = 2;
  static const int DI_TERMINATION_CAUSE_DIAMETER_BAD_ANSWER = 3;
  static const int DI_TERMINATION_CAUSE_DIAMETER_ADMINISTRATIVE = 4;
  static const int DI_TERMINATION_CAUSE_DIAMETER_LINK_BROKEN = 5;
  static const int DI_TERMINATION_CAUSE_DIAMETER_AUTH_EXPIRED = 6;
  static const int DI_TERMINATION_CAUSE_DIAMETER_USER_MOVED = 7;
  static const int DI_TERMINATION_CAUSE_DIAMETER_SESSION_TIMEOUT = 8;
}
